function test_lone_sum()
%  test_lone_sum will test whether the function lone_sum works by
%  comparing known answers to answers generated by lone_sum. This function
%  calls on the function test_function for the comparison.

global error;
error = 0;

test_function(4, 4, 4, 0)
test_function(3, 5, 1, 9)
test_function(3, 5, 3, 5)
test_function(0, 9, 9, 0)
test_function(9, 8, 10, 27)
test_function(2, 2, 1, 1)

if error == 0
    fprintf('The function works!\n')
else
    fprintf('The function has errors\n')
    
end

end

function test_function(a,b,c,answer)
%  test_function tests whether the function lone_sum equals the correct
%  value as determined by people and prints a statement telling the user
%  if the function works or not for the particular input values.

global error;

if lone_sum(a,b,c) == answer
    fprintf('lone_sum(%d,%d,%d) = %d\n', a, b, c, answer)
else
    fprintf('lone_sum(%d,%d,%d) does not equal %d. ERROR\n',...
        a, b, c, answer)
    error = error + 1;
end
            
end

